 export const PLAYER = {
    PREVIOUS_TRACK : 'PREVIOUS_TRACK',
    NEXT_TRACK : 'NEXT_TRACK',
    SHUFFLE_TRACKS : 'SHUFFLE_TRACKS',
    LOOP_SAME_TRACK : 'LOOP_SAME_TRACK',
    LOOP_ALL_TRACKS : 'LOOP_ALL_TRACKS',
    CURRENT_TRACK : 'CURRENT_TRACK'
};

export const SPOTIFY = {
    GET_ACCESS_TOKEN : 'GET_ACCESS_TOKEN',
    GET_TRACK_DETAILS : 'GET_TRACK_DETAILS'
}

export const AUTH = {
    SET_CURRENT_USER : 'SET_CURRENT_USER'
}